const Menu = [
    {
        id:1,
        image:"images/beafBurger.jpg",
        name: "Beaf Burger",
        catagory: "lunch",
        price: "30$",
        description: "Beaf Burger for Eating.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti quae expedita doloribus eaque blanditiis similique, fugit adipisci facilis voluptas dolorum.",
    },
    {
        id:2,
        image:"images/burger.jpg",
        name: "Burger",
        catagory: "breakfast",
        price: "35$",
        description: "Beaf Burger for Eating.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti quae expedita doloribus eaque blanditiis similique, fugit adipisci facilis voluptas dolorum.",
    },
    {
        id:3,
        image:"images/chips.jpg",
        name: "Potato Chips",
        catagory: "lunch",
        price: "10$",
        description: "Beaf Burger for Eating.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti quae expedita doloribus eaque blanditiis similique, fugit adipisci facilis voluptas dolorum.",
    },
    {
        id:4,
        image:"images/greenTea.jpg",
        name: "Green Tea",
        catagory: "breakfast",
        price: "15$",
        description: "Beaf Burger for Eating.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti quae expedita doloribus eaque blanditiis similique, fugit adipisci facilis voluptas dolorum.",
    },
    {
        id:5,
        image:"images/jalebi.jpg",
        name: "Jalebi",
        catagory: "dinner",
        price: "40$",
        description: "Beaf Burger for Eating.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti quae expedita doloribus eaque blanditiis similique, fugit adipisci facilis voluptas dolorum.",
    },
    {
        id:6,
        image:"images/samosa.jpg",
        name: "Samosa",
        catagory: "dinner",
        price: "10$",
        description: "Beaf Burger for Eating.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti quae expedita doloribus eaque blanditiis similique, fugit adipisci facilis voluptas dolorum.",
    },
    {
        id:6,
        image:"images/samosa.jpg",
        name: "MyDish",
        catagory: "mydish",
        price: "10$",
        description: "Beaf Burger for Eating.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Deleniti quae expedita doloribus eaque blanditiis similique, fugit adipisci facilis voluptas dolorum.",
    },
];
export default Menu;